language: php
before_script:
  - composer install --no-interaction

php:
  - '7.1'
  - nightly

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
